trigger:
- master
variables:
 configuration: Release 
stages:
 - stage: Build_Backend_App
   jobs:
     - job: Build_And_Test_And_Create_Build_Artifact
       pool:
        vmImage: ubuntu-latest
       steps:
        - checkout: self
        - task: UseDotNet@2
          inputs:
            packageType: sdk
            version: '10.0.x'
        - script: dotnet restore     
        - script: dotnet build -c $(configuration) 
        - script: dotnet test --no-build
        - script: dotnet publish  EmployeeManagement.API/EmployeeManagement.API.csproj -c $(configuration) -o $(Build.ArtifactStagingDirectory)  
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: $(Build.ArtifactStagingDirectory)
            ArtifactName: drop 

