trigger:
  branches:
    include:
      - master
    
name: $(Date:yyyyMMdd).$(Rev:r)  

variables:
  - group: Common
    
stages:
  - template: templates/build.yml
  
  - template: templates/deploy.yml

    parameters:
      environment: Dev-Environment
      variableGroup: Dev
      dependsOn: Build

  - template: templates/deploy.yml
    parameters:
      environment: QA-Environment
      variableGroup: QA
      dependsOn: Deploy_Development

  - template: templates/deploy.yml
    parameters:
      environment: Prod-Environment
      variableGroup: Prod
      dependsOn: Deploy_QA   