parameters:
- name: configuration
  type: string
- name: DotnetVersion
  type: string

stages:
- stage: Build
  displayName: Build and Test the Solution
  jobs:
  - job: compile
    pool:
     name: Selfhosted Pool
    steps:
    - checkout: self
    - task: UseDotNet@2
      inputs:
       packageType: sdk
       version: ${{Parameters.dotnetVersion}}
    - script: dotnet restore
    - script: dotnet build --configuration ${{Parameters.configuration}}
    - script: dotnet test --no-build  --configuration ${{Parameters.configuration}}
    - script: dotnet publish ./EmployeeManagement.API/EmployeeManagement.API.csproj -c ${{Parameters.configuration}} -o $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
       PathtoPublish: $(Build.ArtifactStagingDirectory)
       ArtifactName: Drop

